package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

	private int id;
	private Ciclo ciclo;
	private Usuario usuario;
	private int curso;
	private Boolean dualIntensiva;

	public Alumno() {
	}

	public Alumno(Ciclo ciclo, Usuario usuario, int curso) {
		this.ciclo = ciclo;
		this.usuario = usuario;
		this.curso = curso;
	}

	public Alumno(Ciclo ciclo, Usuario usuario, int curso, Boolean dualIntensiva) {
		this.ciclo = ciclo;
		this.usuario = usuario;
		this.curso = curso;
		this.dualIntensiva = dualIntensiva;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ciclo getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(Ciclo ciclo) {
		this.ciclo = ciclo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getCurso() {
		return this.curso;
	}

	public void setCurso(int curso) {
		this.curso = curso;
	}

	public Boolean getDualIntensiva() {
		return this.dualIntensiva;
	}

	public void setDualIntensiva(Boolean dualIntensiva) {
		this.dualIntensiva = dualIntensiva;
	}

}
