package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int horasTotales;
	private int curso;
	private int codigo;
	private Set asignaturaCiclos = new HashSet(0);
	private Set horarios = new HashSet(0);

	public Asignatura() {
	}

	public Asignatura(String nombre, int horasTotales, int curso, int codigo) {
		this.nombre = nombre;
		this.horasTotales = horasTotales;
		this.curso = curso;
		this.codigo = codigo;
	}

	public Asignatura(String nombre, int horasTotales, int curso, int codigo, Set asignaturaCiclos, Set horarios) {
		this.nombre = nombre;
		this.horasTotales = horasTotales;
		this.curso = curso;
		this.codigo = codigo;
		this.asignaturaCiclos = asignaturaCiclos;
		this.horarios = horarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getHorasTotales() {
		return this.horasTotales;
	}

	public void setHorasTotales(int horasTotales) {
		this.horasTotales = horasTotales;
	}

	public int getCurso() {
		return this.curso;
	}

	public void setCurso(int curso) {
		this.curso = curso;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Set getAsignaturaCiclos() {
		return this.asignaturaCiclos;
	}

	public void setAsignaturaCiclos(Set asignaturaCiclos) {
		this.asignaturaCiclos = asignaturaCiclos;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

}
