package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

/**
 * AsignaturaCiclo generated by hbm2java
 */
public class AsignaturaCiclo implements java.io.Serializable {

	private Integer id;
	private Asignatura asignatura;
	private Ciclo ciclo;

	public AsignaturaCiclo() {
	}

	public AsignaturaCiclo(Asignatura asignatura, Ciclo ciclo) {
		this.asignatura = asignatura;
		this.ciclo = ciclo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	public Ciclo getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(Ciclo ciclo) {
		this.ciclo = ciclo;
	}

}
