package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String periodo;
	private Set alumnos = new HashSet(0);
	private Set asignaturaCiclos = new HashSet(0);

	public Ciclo() {
	}

	public Ciclo(String nombre, String periodo) {
		this.nombre = nombre;
		this.periodo = periodo;
	}

	public Ciclo(String nombre, String periodo, Set alumnos, Set asignaturaCiclos) {
		this.nombre = nombre;
		this.periodo = periodo;
		this.alumnos = alumnos;
		this.asignaturaCiclos = asignaturaCiclos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	public Set getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set alumnos) {
		this.alumnos = alumnos;
	}

	public Set getAsignaturaCiclos() {
		return this.asignaturaCiclos;
	}

	public void setAsignaturaCiclos(Set asignaturaCiclos) {
		this.asignaturaCiclos = asignaturaCiclos;
	}

}
