package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set reunions = new HashSet(0);

	public Estado() {
	}

	public Estado(String nombre) {
		this.nombre = nombre;
	}

	public Estado(String nombre, Set reunions) {
		this.nombre = nombre;
		this.reunions = reunions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getReunions() {
		return this.reunions;
	}

	public void setReunions(Set reunions) {
		this.reunions = reunions;
	}

}
