package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private String tipo;
	private Set reunionInvitadoses = new HashSet(0);
	private Set reunions = new HashSet(0);

	public Profesor() {
	}

	public Profesor(Usuario usuario, String tipo) {
		this.usuario = usuario;
		this.tipo = tipo;
	}

	public Profesor(Usuario usuario, String tipo, Set reunionInvitadoses, Set reunions) {
		this.usuario = usuario;
		this.tipo = tipo;
		this.reunionInvitadoses = reunionInvitadoses;
		this.reunions = reunions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getReunionInvitadoses() {
		return this.reunionInvitadoses;
	}

	public void setReunionInvitadoses(Set reunionInvitadoses) {
		this.reunionInvitadoses = reunionInvitadoses;
	}

	public Set getReunions() {
		return this.reunions;
	}

	public void setReunions(Set reunions) {
		this.reunions = reunions;
	}

}
