package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

/**
 * ReunionInvitados generated by hbm2java
 */
public class ReunionInvitados implements java.io.Serializable {

	private Integer id;
	private Reunion reunion;
	private Profesor profesor;
	private String estadoInvitacion;

	public ReunionInvitados() {
	}

	public ReunionInvitados(Reunion reunion, Profesor profesor) {
		this.reunion = reunion;
		this.profesor = profesor;
	}

	public ReunionInvitados(Reunion reunion, Profesor profesor, String estadoInvitacion) {
		this.reunion = reunion;
		this.profesor = profesor;
		this.estadoInvitacion = estadoInvitacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Reunion getReunion() {
		return this.reunion;
	}

	public void setReunion(Reunion reunion) {
		this.reunion = reunion;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public String getEstadoInvitacion() {
		return this.estadoInvitacion;
	}

	public void setEstadoInvitacion(String estadoInvitacion) {
		this.estadoInvitacion = estadoInvitacion;
	}

}
