package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set rolUsuarios = new HashSet(0);

	public Roles() {
	}

	public Roles(String nombre) {
		this.nombre = nombre;
	}

	public Roles(String nombre, Set rolUsuarios) {
		this.nombre = nombre;
		this.rolUsuarios = rolUsuarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getRolUsuarios() {
		return this.rolUsuarios;
	}

	public void setRolUsuarios(Set rolUsuarios) {
		this.rolUsuarios = rolUsuarios;
	}

}
