package objetos;
// Generated 22 feb 2025, 16:06:35 by Hibernate Tools 6.5.1.Final

/**
 * RolUsuario generated by hbm2java
 */
public class RolUsuario implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private Roles roles;

	public RolUsuario() {
	}

	public RolUsuario(Usuario usuario, Roles roles) {
		this.usuario = usuario;
		this.roles = roles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

}
